### ISSUE TITLE
Отпечатка

### ISSUE THREAD

**Issue by dmitryi365** [OpenFarLands/ServerRules#1]
![Screenshot_20240130-103213_Chrome](https://github.com/OpenFarLands/ServerRules/assets/52741336/5244041d-a881-40d8-9c28-933672363965)

своб/свою

**Comment by mikhaillav** [comment]
Исправлено в этом [коммите](https://github.com/OpenFarLands/ServerRules/commit/8227906ba89cc97a0cbcde10728b32d432b4308a)
